# Site settings
title: Eero Lihavainen 
tagline:  
email: eeelliha@gmail.com
description: > # this means to ignore newlines until "baseurl"
    Blogging about things and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eerlich.github.io" # the base hostname & protocol for your site
#twitter_username:  
github_username: eerlich 
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
